# Generated by Django 4.1.1 on 2023-08-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_typename', models.CharField(max_length=30)),
                ('typename_bgpic', models.ImageField(upload_to='static/gallerypic')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(default=False, max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('messagge', models.TextField()),
            ],
        ),
    ]
